# Generated by Django 4.2.5 on 2023-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назавание'),
        ),
    ]
